/**
  ******************************************************************************
  * @file    dac_example.c
  * @author  Auto-generated by Claude Code
  * @version V1.0.0
  * @date    24-August-2025
  * @brief   DAC driver usage example
  ******************************************************************************
  * @attention
  *
  * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
  * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
  * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
  * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
  * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
  * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
  *
  * COPYRIGHT 2025 GIGADEVICE
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "gd32f10x_dac.h"
#include "gd32f10x_gpio.h"
#include "gd32f10x_rcc.h"
#include "FreeRTOS.h"
#include "task.h"

/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/
#define DAC_TASK_PRIORITY       ( tskIDLE_PRIORITY + 2 )
#define DAC_TASK_STACK_SIZE     ( configMINIMAL_STACK_SIZE * 2 )

/* Private macro -------------------------------------------------------------*/
/* Private variables ---------------------------------------------------------*/
DAC_InitTypeDef DAC_InitStructure;
uint16_t dac_value = 0;
uint8_t direction = 1;  // 1 for increasing, 0 for decreasing

/* Private function prototypes -----------------------------------------------*/
void DAC_GPIO_Config(void);
void DAC_Config(void);
void DAC_Task(void *pvParameters);

/* Private functions ---------------------------------------------------------*/

/**
  * @brief  Configure the DAC GPIO ports.
  * @param  None
  * @retval None
  */
void DAC_GPIO_Config(void)
{
    GPIO_InitTypeDef GPIO_InitStructure;

    /* Enable GPIOA clock */
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA, ENABLE);

    /* Configure PA4 (DAC Channel 0) as analog output */
    GPIO_InitStructure.GPIO_Pin = GPIO_PIN_4;
    GPIO_InitStructure.GPIO_Mode = GPIO_MODE_AIN;
    GPIO_Init(GPIOA, &GPIO_InitStructure);
}

/**
  * @brief  Configure the DAC interface.
  * @param  None
  * @retval None
  */
void DAC_Config(void)
{
    /* Enable DAC clock */
    RCC_APB1PeriphClockCmd(RCC_APB1Periph_DAC, ENABLE);
    
    /* DAC channel0 configuration */
    DAC_InitStructure.DAC_Trigger = DAC_TRIGGER_NONE;
    DAC_InitStructure.DAC_WaveGeneration = DAC_WAVEGENERATION_NONE;
    DAC_InitStructure.DAC_LFSRUnmask_TriangleAmplitude = DAC_LFSRUNMASK_BIT0;
    DAC_InitStructure.DAC_OutputBuffer = DAC_OUTPUTBUFFER_ENABLE;
    DAC_Init(DAC_CHANNEL_0, &DAC_InitStructure);
    
    /* Enable DAC Channel0 */
    DAC_Cmd(DAC_CHANNEL_0, ENABLE);
}

/**
  * @brief  DAC Task.
  * @param  pvParameters: pointer that will be passed to the task
  * @retval None
  */
void DAC_Task(void *pvParameters)
{
    while(1)
    {
        // Generate a ramp waveform
        if(direction)
        {
            dac_value += 100;
            if(dac_value >= 4095)
            {
                dac_value = 4095;
                direction = 0;
            }
        }
        else
        {
            dac_value -= 100;
            if(dac_value <= 0)
            {
                dac_value = 0;
                direction = 1;
            }
        }
        
        // Set DAC Channel0 output value
        DAC_SetChannel1Data(DAC_ALIGN_12B_R, dac_value);
        
        // Delay for waveform visibility
        vTaskDelay(50 / portTICK_RATE_MS);
    }
}

/**
  * @brief  Main program
  * @param  None
  * @retval None
  */
int main(void)
{
    /* Configure DAC GPIO ports */
    DAC_GPIO_Config();
    
    /* Configure DAC interface */
    DAC_Config();
    
    /* Create DAC task */
    xTaskCreate(DAC_Task, "DAC_Task", DAC_TASK_STACK_SIZE, NULL, DAC_TASK_PRIORITY, NULL);
    
    /* Start the scheduler */
    vTaskStartScheduler();
    
    /* Should never reach here */
    while(1);
}