/**
  ******************************************************************************
  * @file    pwm_example.c
  * @author  Auto-generated by Claude Code
  * @version V1.0.0
  * @date    24-August-2025
  * @brief   PWM driver usage example
  ******************************************************************************
  * @attention
  *
  * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
  * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
  * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
  * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
  * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
  * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
  *
  * COPYRIGHT 2025 GIGADEVICE
  ******************************************************************************
  */

/* Includes ------------------------------------------------------------------*/
#include "gd32f10x_pwm.h"
#include "gd32f10x_gpio.h"
#include "gd32f10x_rcc.h"
#include "FreeRTOS.h"
#include "task.h"

/* Private typedef -----------------------------------------------------------*/
/* Private define ------------------------------------------------------------*/
#define PWM_TASK_PRIORITY       ( tskIDLE_PRIORITY + 2 )
#define PWM_TASK_STACK_SIZE     ( configMINIMAL_STACK_SIZE * 2 )

/* Private macro -------------------------------------------------------------*/
/* Private variables ---------------------------------------------------------*/
PWM_InitTypeDef PWM_InitStructure;
uint16_t duty_cycle = 0;
uint8_t direction = 1;  // 1 for increasing, 0 for decreasing

/* Private function prototypes -----------------------------------------------*/
void PWM_GPIO_Config(void);
void PWM_Config(void);
void PWM_Task(void *pvParameters);

/* Private functions ---------------------------------------------------------*/

/**
  * @brief  Configure the PWM GPIO ports.
  * @param  None
  * @retval None
  */
void PWM_GPIO_Config(void)
{
    GPIO_InitTypeDef GPIO_InitStructure;

    /* Enable TIMER0 clock */
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_TIMER0, ENABLE);
    
    /* Enable GPIOA clock */
    RCC_APB2PeriphClockCmd(RCC_APB2Periph_GPIOA, ENABLE);

    /* Configure PA8 (TIMER0 CH0) as alternate function push-pull */
    GPIO_InitStructure.GPIO_Pin = GPIO_PIN_8;
    GPIO_InitStructure.GPIO_Mode = GPIO_MODE_AF_PP;
    GPIO_InitStructure.GPIO_Speed = GPIO_SPEED_50MHZ;
    GPIO_Init(GPIOA, &GPIO_InitStructure);
}

/**
  * @brief  Configure the PWM interface.
  * @param  None
  * @retval None
  */
void PWM_Config(void)
{
    /* TIMER0 configuration */
    PWM_InitStructure.PWM_Channel = PWM_CHANNEL_0;
    PWM_InitStructure.PWM_Frequency = 1000;  // 1KHz
    PWM_InitStructure.PWM_DutyCycle = 0;     // Start with 0% duty cycle
    PWM_InitStructure.PWM_CounterMode = PWM_COUNTERMODE_UP;
    PWM_InitStructure.PWM_OCMode = PWM_OCMODE_PWM1;
    PWM_InitStructure.PWM_OCPolarity = PWM_OCPOLARITY_HIGH;
    PWM_InitStructure.PWM_OutputState = ENABLE;
    PWM_InitStructure.PWM_OutputNState = DISABLE;
    PWM_InitStructure.PWM_OCIdleState = PWM_OCIDLESTATE_RESET;
    PWM_InitStructure.PWM_OCNIdleState = PWM_OCNIDLESTATE_RESET;
    
    PWM_Init(TIMER0, &PWM_InitStructure);
    
    /* Enable TIMER0 */
    PWM_Cmd(TIMER0, ENABLE);
}

/**
  * @brief  PWM Task.
  * @param  pvParameters: pointer that will be passed to the task
  * @retval None
  */
void PWM_Task(void *pvParameters)
{
    while(1)
    {
        // Update duty cycle for fading effect
        if(direction)
        {
            duty_cycle++;
            if(duty_cycle >= 100)
            {
                duty_cycle = 100;
                direction = 0;
            }
        }
        else
        {
            duty_cycle--;
            if(duty_cycle == 0)
            {
                direction = 1;
            }
        }
        
        // Set the new duty cycle
        PWM_SetCompare1(TIMER0, (PWM_InitStructure.PWM_Frequency * duty_cycle) / 100);
        
        // Delay for visibility of fading effect
        vTaskDelay(20 / portTICK_RATE_MS);
    }
}

/**
  * @brief  Main program
  * @param  None
  * @retval None
  */
int main(void)
{
    /* Configure PWM GPIO ports */
    PWM_GPIO_Config();
    
    /* Configure PWM interface */
    PWM_Config();
    
    /* Create PWM task */
    xTaskCreate(PWM_Task, "PWM_Task", PWM_TASK_STACK_SIZE, NULL, PWM_TASK_PRIORITY, NULL);
    
    /* Start the scheduler */
    vTaskStartScheduler();
    
    /* Should never reach here */
    while(1);
}